### ISSUE TITLE
Please stop importing all of lodash

### ISSUE THREAD

**Issue by Whoaa512** [ParabolInc/falcor-saddle#5]
Since v4 of lodash it's easy to only import the few functions you need

e.g. `import get from 'lodash/get'`

And it reduces the bundle size which can be a concern if you're creating AWS lambda functions.

**Comment by jordanh** [comment]
Good idea! Did you try falcor-saddle? We switched [our project](https://github.com/ParabolInc/action) to use GraphQL (and [Cashay](https://github.com/mattkrick/cashay)) instead...but if there is a user community around falcor-saddle I'd be happy to make the revision.

**Comment by Whoaa512** [comment]
Yup, currently in the process of building out API endpoints for a new product with falcor-saddle. I'll be in crunch mode for the next 6 weeks but I'd be happy to contribute back after that.

Curious, what caused you to switch your project over to GraphQL with Cashay?

**Comment by jordanh** [comment]
Well, I'll be! That's great to hear.

I took a few minutes and merged #6 to remove the production dependency on lodash altogether. I've learned a few things about ES6 over the past 18 months 😉  Please let me know how v0.1.1 suits you.

When @mattkrick joined the team, he helped us port our vestigial application from node+express+falcor to the [meatier](https://github.com/mattkrick/meatier) stack. I wrote a post about it here: https://focus.parabol.co/a-meatier-future-e8231c161c3c#.qhuuh8zev

On the bottom end, our application uses a lot of live socket data. On the top end, we render that data using redux and react. To continue using Falcor we would have had to solve how to distribute live data _and_ shoe-horn it into redux. Matt began writing Cashay to solve how to distribute live data and it all gets stored in redux automatically. Writing Cashay ended up locking us into GraphQL pretty tightly. 

There are still some things I really like about Falcor. I find the its graph query path syntax pretty wonderful, for example. I hope it keeps maturing!

**Comment by Whoaa512** [comment]
That's awesome, thanks! Left one comment about your switch from `_.defaults` to `Object.assign`.

Thanks for the explanation as well. Always interesting to hear how the business need drives the technology choice :)

**Comment by jordanh** [comment]
Good catch! Ok, I just published v0.1.2. Thank you.

I'm likewise looking forward to hearing about how your product build goes!
